### ISSUE TITLE
sqlInterpolate would be useful to use with dbQuoteIdentifier

### ISSUE THREAD

**Issue by jsonbecker** [r-dbi/DBI#192]
Right now `sqlInterpolate` uses `dbQuoteString`, but sometimes I want to write a function to produce a query where I pass in table names and other identifiers. I don't have a great idea for the API to mix and match as desired, but it'd be nice to be able to.

Maybe something like:

```
sqlInterpolate(connection, ..., .quote_method)
```

where you can supply something like `c('string','identifier'...)` etc to walk along `...` or `.dots`?

**Comment by hadley** [comment]
I think this is out of scope for `sqlInterpolate()`, because it's designed as a fallback for databases/drivers that don't have support for query interpolation.

**Comment by krlmlr** [comment]
Maybe `sqlInterpolate()` should use the new `dbQuoteLiteral()`?

**Comment by nriley** [comment]
Using something extensible such as `dbQuoteLiteral` makes sense to me rather than the current behavior of 'quote it if it's a string, otherwise just pass it through'.  I'm running into a problem where dates I pass to sqlInterpolate aren't getting escaped at all:

```r
> str(order_date)
 POSIXct[1:1], format: "2018-07-03"
> sqlInterpolate(db, 'SELECT ?foo FROM DUAL', foo = order_date)
<SQL> SELECT 2018-07-03 FROM DUAL
```
(this is ROracle which doesn't support named bind parameters, which is the reason I'm using sqlInterpolate at all...)

Ideally I could do something like this:

```R
> dbQuoteLiteral(ANSI(), order_date)
<SQL> '20180703000000'
# Oops, this is the generic version...
> setMethod('dbQuoteLiteral', signature('OraConnection', 'POSIXt'), function(conn, x)
  SQL(paste0("TO_DATE('", strftime(as.POSIXct(x), "%Y%m%d%H%M%S", tz="UTC"), "', 'YYYYMMDDHH24MMSS')")))
[1] "dbQuoteLiteral"
> dbQuoteLiteral(ANSI(), order_date)
<SQL> '20180703000000'
> dbQuoteLiteral(db, order_date)
<SQL> TO_DATE('20180703000000', 'YYYYMMDDHH24MISS')
```
but this doesn't affect sqlInterpolate (yet).

**Comment by krlmlr** [comment]
Using `dbQuoteLiteral()` since bf995dd.
