### ISSUE TITLE
Problem with dbWithTransaction 

### ISSUE THREAD

**Issue by NavyaSindhu** [r-dbi/DBI#228]
I am trying to write data to SQL tables using transactions so that if any of the insertion fails, I want to revert all insertions done as part of transactions. Following is the code 

tryCatch(
dbWithTransaction(conn, {
  dbExecute(conn, "INSERT INTO trail (speed, dist) VALUES (1, 1);")
  dbExecute(conn, "INSERT INTO trail (speed, dist) VALUES (2 2);")
  dbExecute(conn, "INSERT INTO trail (speed, dist) VALUES (3, 3);")
}),
error = function(){
  dbRollback(conn)
}
)
dbDisconnect(conn)

Since I have introduced error intentionally in second statement, I expect transaction rollback.
In actual, RStudio is locking trail table which can be seen through sp_who2. until and unless, RStudio session is quit, we'll not be able to perform any operations around trail table.

How to perform rollback on transaction failure?

**Comment by krlmlr** [comment]
Thanks. `dbWithTransaction()` should roll back the transaction automatically, even without the `error` handler. Which database backend are you using, *odbc*, *RSQLServer* or something else?

**Comment by aryoda** [comment]
If you are using the Microsoft SQL Server (what `sp_who2` indicates) and the `odbc` package you may be affected by a "table lock not released" bug in `odbc` that has been fixed by Jim Hester March 22:

https://github.com/r-dbi/odbc/issues/138

Try to update your `odbc` package directly from github (unit a new CRAN version is released) and see if it works:

`
devtools::install_github("r-dbi/odbc")
`

Please report your result here then to be able to close the ticket (if it works).

**Comment by krlmlr** [comment]
Thanks @aryoda for the information and the link. I'm closing the issue, please open a new issue if problems persist.
