### ISSUE TITLE
Guidelines to handle schemes and views

### ISSUE THREAD

**Issue by zozlak** [r-dbi/DBI#24]
I rise my issue here, because I think it would be valuable to decide such things on the "top level", so implementations of the DBI API can be compiliant one with the other and provide users with a really unified API.

Wide variety of modern database systems supports:
- many schemes per database;
- views;

but there are no official guidelines how to handle that in packages implementing the DBI API.

There is a nottice in dbGetTables() description that "This should, where possible, include temporary tables.". Is it possible to add a similar notice regarding views? And maybe also in dbReadTable() description?
I am asking about it because views play a vital role for both:
- assuring user privileages;
- making complicated database structures available for "everyday users";

and ommiting them in DBI API implementations dramatically reduce their functionality.
This is even more painful as dplyr uses DBI database connectivity backends.

The schemes issue is more complicated. DBI wanted a table to be identified by simple a name. For database systems which support multiple schemes per database a clarification is needed:
- Does a schema name (if other the default scheme) should be the part of the "DBI table name"? (which by the way is simply wrong, because we can not assure proper escaping, anyway it works like that in some DBI implementations)
- Or maybe DBI drivers are by definition limited to use only a default scheme?
- Or maybe DBI should define other (but common for all DBI compiliant drivers) way to deal with schemes?

I checked RPostgreSQL, RMySQL and ROracle and they deal with scheme in different way:
- RMySQL pretends that there is no such things like schemes even MySQL supports schemes (in its own way, by mapping them to databases, but anyway);
- ROracle functions take an additional and optional "scheme" parameter;
- RPostgreSQL functions accept the "name" parameter to be a character vector; in such a case they take the first element of the vector as schema name and the second as table name.

And checking onother DBI API implementations would probably make this list longer.
This inconsistency limits the usage of the DBI API when it cames to handle schemes.

**Comment by krlmlr** [comment]
- Views and temporary tables should be returned with `dbListTables()`
- DBI should officially support multi-component table names (mostly for `dbReadTable()` and `dbWriteTable()`) that are combined to a single identifier with the help of a new `dbBuildIdentifier(Connection, character)`; the latter defaults to quoting the individual names and combining them with a `"."`

I think everything can be tested in a generic fashion in the DBItest package.

**Comment by krlmlr** [comment]
Need schema in `dbListTables()`

**Comment by krlmlr** [comment]
dbBuildIdentifier() or dbQuoteIdentifier()?

**Comment by zozlak** [comment]
> Need schema parameter in dbListTables(), default to "current schema"

On one hand I fully support your request but on the other this will be backward-incompatible change in the API. It is against CRAN guidelines and as DBI is quite widely used it is a really serious thing. 

Although I can imagine solutions which will not break backward compatibility (e.g. passing schemas vector as an attribute of the returned vector) it will be rather inconvenient for the user.

Taking this into account maybe it would be better to introduce a new function and mark dbListTables() as deprecated...

**Comment by hadley** [comment]
@zozlak how will it be a backward incompatible change?

(And backward incompatible changes aren't against CRAN policy as long as you give everyone adequate notice about the change)

**Comment by krlmlr** [comment]
From the policies:

> If an update will change the package’s API and hence affect packages depending on it, it is expected that you will contact the maintainers of affected packages and suggest changes, and give them time to prepare updates before submitting your updated package. Do mention in the submission email which packages are affected and that their maintainers have been informed. In order to derive the reverse dependencies of a package including the addresses of maintainers who have to be notified upon changes, the function reverse_dependencies_with_maintainers is available from the developer website.

**Comment by zozlak** [comment]
> @zozlak how will it be a backward incompatible change?

If I want to keep current return type (character vector, one element per table), then I should either join schema name and table name (probably properly escaped) either do some strange things (like assign schema names to attribute).
The problem with returning joined schema and table name is that:
- if I return them unescaped, then it may be impossible to distinguish table name from schema name;
- it I want to return them in escaped form I have a problem, because different database systems use different escapes for objects identifiers.

And anyway if we agree that other functions (dbReadTable(), etc.) should take schema and table name separated from each other (e.g. as a two-element character vector), to be able to escape them properly, then I would expect dbListTables() to return schema and table name separately.

Now if I want to return schema name separated from table name and do it in a natural way it would mean for me to return them as a character matrix (or data frame) with schema and table name in separate columns but this would change return type of dbListTables() (and so will be backward incompatible).

Or am I missing something?

**Comment by krlmlr** [comment]
I think dbListTables() should keep returning a plain character vector with unquoted names. The schema should be specified as input parameter.

**Comment by zozlak** [comment]
@kiril I like your idea. It will make change totally transparent for those who don't care about schemes and at the same time allow to use schemes for those who need them.

Then we would also need dbListSchemes()

**Comment by krlmlr** [comment]
- Views should be treated the same as tables
- Multi-component table names: Two options:
    - Character vector -> several problems
    - Preferred: New function `dbTableName(Connection, character) -> SQL`

**Comment by hadley** [comment]
`dbReadTable()` and `dbWriteTable()` would take character vectors and would call `dbTableName()` for you.

**Comment by beanumber** [comment]
I like that VIEWs are returned by `dbListTables`, but does it bother anyone that VIEWs can't be destroyed by `dbRemoveTable`? Can we add `dbRemoveView`? Or a flag to `dbRemoveTable` to `DROP VIEW` instead of `DROP TABLE`?

**Comment by krlmlr** [comment]
@beanumber: They can't be created by dbCreateTable() either. Please open a new issue to discuss view creation and destruction, I'm removing this comment and yours to keep the thread clean.

**Comment by krlmlr** [comment]
`dbReadTable(SQL("SELECT * FROM a WHERE x = 1"))` should look for a table named `SELECT * FROM a WHERE x = 1`. This has given us headaches with RSQLite, because some packages did the quoting themselves.

Currently, the design for schema support looks like this:

- The `dbQuoteIdentifier()` generic gains an optional `namespace` argument that allows prepending namespace components. This expects a character vector that will be passed to `dbQuoteIdentifier(..., namespace = NULL)` (again) before connecting the components. If length 0, no namespace is prepended
- The `dbReadTable()`, `dbWriteTable()`, `dbExistsTable()` and `dbRemoveTable()` gain a default implementation that allows passing a list as `name` argument; this will then be used in a call to `dbQuoteIdentifier()` to simplify passing the namespace to these methods
- There will be a new `dbListNamespaces()` generic, TBD
- The `dbListTables()` method also gains an optional `namespace` argument, which can also be a list

**Comment by krlmlr** [comment]
Another option: `dbReadTable()` et al. are expected to always pass `...` along to `dbQuoteIdentifier()`.

**Comment by krlmlr** [comment]
Next iteration of the design:

- `dbQuoteIdentifier()` methods use `...` to extend an identifier with namespace components. DBI will give suggestions but not enforce anything. The default should not add any namespace components.
- All methods that take a table name (`dbReadTable()`, `dbWriteTable()`, `dbExistsTable()`, `dbRemoveTable()`, ...) call `dbQuoteIdentifier(conn, x = name, ...)`, this allows specifying namespace components as parts of a call to these methods.
- There will be a new `dbListSchemas()` generic, this will return a data frame with a list column that contains the schema specification; this will have to be used in the `dbQuoteIdentifier()` call to access this schema. The default empty schema is always part of this list.
- `dbListTables()` methods use `...` to specify the namespace just like `dbQuoteIdentifier()` does.

**Comment by hadley** [comment]
I think an approach around creating an explicit identifier class might be simpler, requiring fewer changes to existing functions.

```R
dbQuoteIdentifier(con, dbIdentifier("database", "schema", "name"))

# or
my_schema <- dbIdentifier("database", "schema")
dbQuoteIdentifier(con, c(my_schema, "name"))

dbReadTable(con, dbIdentifier("database", "schema", "name")))

dbListNamespaces(con)$namespaces
[[1]]
dbIdentifier()

[[2]]
dbIdentifier("database", "schema")
...

dbListTables(con, dbName("database", "schema", name)
```

**Comment by hadley** [comment]
It might also be better to have separate `dbListDatabases()` and `dbListSchemas()`.  I don't think SQL has good existing notion of namespace.

**Comment by zozlak** [comment]
I like Hadley's approach of creating an explicit identifier class.

Database vendors differ a lot when it comes to identifiers (e.g. Ms SQL allows to include both database name and schema name in the identifier, Postgresql allows schema name, MySQL allows database name and some vendors support only plain table name).

Modelling all these differences as separate parameters taken by quite many functions of the API looks problematic to me. It will be difficult to maintain and inflexible (and for sure there are other vendors with other strange ways of constructing identifiers).

Having a separate identifier class will allow to keep the rest of the API immutable to any future changes in the way identifiers are constructed.

I also think that having separate `dbListDatabases()` and `dbListSchemas()` is a good idea. The concept of "a namespace" would be something invented by the DBI. In my opinion it is better to stick to terms already existing in the SQL world which are databases and schemas.

Last but not least sorry for interrupting your discussion by someone not involved in the development.

**Comment by krlmlr** [comment]
Thanks @zozlak for your input, I agree that we probably don't want to use `...` to hold database/schema components.

I think we need two components:

1. A way to pass through table/view identifiers with database/schema/... qualification
2. A way to list databases, schemas, ...

For the first, we already have the `SQL` class, but even the upcoming [DBI specification](http://rstats-db.github.io/DBI/articles/spec.html) doesn't enforce but only only suggests using it -- instead it specifies that quoted identifiers are immune to calls to `dbQuoteIdentifier()`, i.e., that `dbQuoteIdentifier(con, x)` is identical to `x` if it is already quoted. `dbWriteTable()` et al. are specified so that they accept a quoted identifier.

For the second, I'd like to define a generic `dbListObjects()` that returns a data frame with a `name` column. The data frame can contain other columns, but the names should be prefixed with a dot, so that we can extend the spec later. The `name` column is expected to contain a quoted identifier (e.g., of class `SQL`). `dbListObjects(con)` lists top-level objects (such as databases), and `dbListObjects(con, name)` list objects in the `name` database/schema/... (whatever applies to your DBMS, hence my choice of "namespace" as a neutral word). We could also define that `dbListObjects(con, NA)` lists the tables/views in the current namespace.

**Comment by zozlak** [comment]
> I think we need (...) a way to pass through table/view identifiers with database/schema/... qualification
> (...)
> For the first, we already have the SQL class

I think the tricky thing is we want to store such identifiers in way allowing us to easily obtain both escaped and unescaped form of the identifier. The `SQL` class does not fulfil the latter one.

When @hadley proposed a separate class for table/view identifiers I understood it like a data structure allowing us to store unescaped database, schema and table/view names components separately.
In such a solution all function listing database objects (no matter if we want to list databases, schemas or tables/views) always return a set of `dbIdentifier` objects and all function interacting with database objects identify them using `dbIdentifier` as well (and if they are given a character vector instead they silently promote it to `dbIdentifier`).

**Comment by iangow** [comment]
SQLAlchemy has faced a lot of these issues, I guess, and might provide ideas.

**Comment by krlmlr** [comment]
@iangow: I have found ["Specifying the Schema Name"](http://docs.sqlalchemy.org/en/latest/core/metadata.html#specifying-the-schema-name) in the SQLAlchemy docs, but there the schema is simply an optional string. Would you like to share a more specific example, or a pointer to documentation?

**Comment by krlmlr** [comment]
@zozlak: Why would we need/want to retrieve the unquoted form of an identifier given as an instance of the `SQL` class?

**Comment by zozlak** [comment]
@krlmlr: E.g. to be able to print it nicely. Also to keep it database vendor agnostic as long as possible. The latter is useful e.g. for the `dplyr` which is able to copy data between different database backends. When you want to make such a copy between backends using different identifier escaping methods and/or allowing different degree of freedom with addressing tables/views (see my comment from March 5th) you need to be able to access each table/view name component separately and you need them to be in unescaped form.

**Comment by krlmlr** [comment]
I'm fine with printing the quoted version of any fully qualified table identifier. I agree that we want the unquoted form for column names, but not necessarily for fully qualified table identifiers. Copying between backends in dplyr seems to mean that you have the full (quoted) name of the source and construct the name of the target in a database-specific way.

I'm willing to keep it simple at this point and attempt a solution without an explicit identifier class. Let's see how far we can get with such a solution, it's easy enough to add an identifier class on top, but I'd rather avoid it if it's not necessary.

**Comment by iangow** [comment]
Regarding the request for examples of SQLAlchemy usage, here's a simple one:

```python
msi = Table('msi', meta, schema='crsp', autoload=True, autoload_with=engine)
```
This is analogous in what it produces to

```r
msi <- tbl(pg, sql("SELECT * FROM crsp.msi"))
```

`RPostgreSQL` has allowed one to do (something like) `dbReadTable(pg, c("crsp", "msi"))`. An alternative approach would seem to be  `dbReadTable(pg, "crsp", schema = "msi")`. Other cases might be `dbListTables(pg, schema = "crsp")`.

In `dplyr`, it would be great to have (for example), `compute(df, name = "msi", schema = "crsp", temporary = FALSE)`. (As it is, I end up doing some pretty clunky SQL to move a table into the appropriate schema.) Having a `schema` argument that can be passed along might be the simplest approach (and appears to be what SQLAlchemy has).

Where SQLAlchemy might offer suggestions is in handling the various ways that the different database providers refer to things. In some ways, MySQL *databases* feel a bit like PostgreSQL *schemas*, but it seems that SQLAlchemy has not treated these as equivalent (and presumably for good reasons). It looks like `schema = ` arguments are specific to PostgreSQL and SQL Server.

[Here](http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html) it says: 

> **Best Practices for PostgreSQL Schema reflection**
> 
> The description of PostgreSQL schema reflection behavior is complex, and is the product of many years of dealing with widely varied use cases and user preferences. But in fact, there’s no need to understand any of it if you just stick to the simplest use pattern: leave the `search_path` set to its default of `public` only, never refer to the name `public` as an explicit schema name otherwise, and refer to all other schema names explicitly when building up a `Table` object. The options described here are only for those users who can’t, or prefer not to, stay within these guidelines.

**Comment by iangow** [comment]
`dbReadTable(con, dbIdentifier("database", "schema", "name")))` seems to build in a redundant reference to `"database"` in that that is typically embedded in `con`. If one could name the arguments to `dbIdentifier` and the order were reversed, one could skip `"database"` argument.

For example, `dbReadTable(con, dbIdentifier("name", schema = "schema"))` would seem to order arguments to reflect the normal usage (i.e., always specifying `table`, sometimes specifying `schema`, and less often seeing a need to specifically refer to `database`, which is currently embedded in `con`) . (Also, something *shorter* like `dbID` would look more elegant: `dbReadTable(con, dbID("name", schema = "schema"))`).

I have a lot of code that is designed to run on different databases in which schemas are organised in a consistent fashion. I can point `R` at different servers thus (I often don't have control over the fact that the names of databases):

```r
Sys.setenv(PGHOST="some_host", PGDATABASE="some_database")
```
Having done that, I can do `pg <- src_postgres()` in code that is agnostic as to which database it is connected to.

If `dbIdentifier` requires a fixed order of unnamed arguments  then `dbIdentifier("database", "schema", "name")))`, then I would need an inelegant `dbIdentifier( Sys.getenv("PGHOST"), "schema", "name")))`.

**Comment by hadley** [comment]
@iangow I think the intent of `dbIdentifier("database", "schema", "name"))` is to explicitly refer to a non-current database. You'd normally use `dbIdentifier("schema", "name")`, or just `dbIdentifier("schema")`. IOTW `dbIdentifier()` uses ..., not named arguments (which I think I'd prefer to avoid because I'm not sure how consistently database, schema etc are used across databases)

I like idea of calling it `dbId()`

**Comment by iangow** [comment]
I might have stepped into the conversation midstream (and I might have got here from another issue where what I was saying is more relevant). 

Where I was coming from is the gap I see as a PostgreSQL user regarding the ability to refer to schemas in an elegant fashion. For example, `tbl(pg, table("some_table", schema="some_project")`, `dbListTables(schema = "some_project")`, or `compute(name = "some_table", schema = "some_project")`. Somewhere else you pointed out that one can do `tbl(pg, sql("SELECT * FROM some_project.some_table"))` (and I have a lot of code like that), but it gets much less elegant for the other two cases.

If you're a MySQL user, you might want `dbIdentifier("database", "table")` (it's been a while since I used MySQL). If you're a PostgreSQL user, you might want `dbIdentifier("schema", "table")` in an analogous setting. Perhaps the idea is for the DBI implementations to recognise that `dbIdentifier("x", "y")` means *schema* and *table* for PostgreSQL and *database* and *table* for MySQL (and assuming that MySQL "databases" are really "schemas" seems risky). But I am not sure if such "transparency" is a good thing. In this setting, using named arguments might make handling different approaches easier.

**Comment by hadley** [comment]
I don't think it's confusing that `dbId("x")` refers to something in the current context (what ever that is), `dbId("y", "x")` refers to something in the parent context etc.

**Comment by iangow** [comment]
OK. These would all work for my wish list.

```r
tbl(pg, dbID("some_schema", "some_table"))
dbListTables(dbId("some_schema"))
compute(dbId("some_schema", "some_table"))
```

(Actually, `compute(dbId("some_schema", "some_table"), overwrite = TRUE)` would be great, but that's a different issue.)

**Comment by krlmlr** [comment]
Thanks for your input. I'm still confident that we can make do without a `dbId()` method (which would really need to be called as `dbId(con, ...)`), but I'll come back to the discussion if it turns out that we do need a `dbId()`.

The approach I'm anticipating is described in https://github.com/rstats-db/DBI/issues/24#issuecomment-284558839, I'm repeating it below (slightly modified). We will not be able to decompose fully qualified table names into their components (cluster, database, schema, ...), but I'd argue we don't need to.

---

I think we need two components:

1. A way to pass through table/view identifiers with database/schema/... qualification
2. A way to list databases, schemas, ...

For the first, we already have the `SQL` class, but even the [DBI specification](http://rstats-db.github.io/DBI/articles/spec.html) doesn't enforce but only only suggests using it -- instead it specifies that quoted identifiers are immune to calls to `dbQuoteIdentifier()`, i.e., that `dbQuoteIdentifier(con, x)` is identical to `x` if it is already quoted. `dbWriteTable()` et al. are specified so that they accept a quoted identifier.

For the second, I'd like to define a generic `dbListObjects()` that returns a data frame with (at least) a `name` column and a `is_table` column. The data frame can contain other columns, but the names should be prefixed with a dot, so that we can extend the spec later. The `name` column is expected to contain a quoted identifier (e.g., of class `SQL`), the `is_table` column is `TRUE` if the row refers to a table or view. `dbListObjects(con)` lists top-level objects (such as databases), and `dbListObjects(con, name)` list objects in the `name` database/schema/... (whatever applies to your DBMS). We could also define that `dbListObjects(con, NA)` lists the tables/views that are accessible without qualification.

**Comment by stephlocke** [comment]
Schema support is vital for working with big/enterprise databases.

In terms of what to expose as metadata - it'd be nifty if you could support the range of information_schema exposed concepts. [information_schema](https://en.wikipedia.org/wiki/Information_schema) is an ansi compliant metadata schema that can be leveraged for getting consistent results across databases.

`dbIdentifier()` as a way to provide schema and database names would be an OK way to go - it doesn't add too much typing. It'd also be good if you did something like `dbId(dbConn,"[dbo].[orders]")`  and have that end up with the correct reference to the table.

**Comment by zozlak** [comment]
> "[dbo].[orders]"

example provided by @stephlocke makes me thinking about the approach proposed by @krlmlr .
I think the `SQL` class is not enough to pass table/view identifiers with database/schema/... qualification because `my.tab` can mean *table "tab" in schema (or database) "my"* as well as *table "my.tab" in current context* and the `SQL` class is unable to distinguish between these usecases. My impression is that the `dbId()` approach is really needed to solve such issue.

By the way while reading discussion about the`dbId` class I see two different approaches:

1. The `dbId` object itself being "not aware" of the database entity type it is representing, e.g.:
    * in `dbReadTable(con, dbId('foo'))` *foo* denotes *a table/view named foo*
    * in `dbListTables(dbId('foo'))` *foo* denotes *container for tables named foo* (in most RDBMSs the *foo* schema, in MySQL the *foo* database) 
    * in `dbListSchemas(dbId('foo'))` *foo* denotes *container for schemas named foo* (in all RDBMSs I know the *foo* database)
2. The `dbId` object storing information about the entity type it is representing.

While the first approach provides users with short and intuitive syntax only the latter one will work with the `dbListObjects()` function proposed by @krlmlr. In the first case the `dbListObjects()` won't know what kind of database entities to list. Alternatively we can assume that the `dbListObjects()` lists all kinds of database entities (which doesn't sound good to me) but then looking at the `dbId` objects returned by it we can't tell, what kind of database entity they represent which is similarly problematic.

**Comment by jimhester** [comment]
I just implemented a simple version of this for **odbc**, https://github.com/rstats-db/odbc/compare/SQLTable?expand=1#diff-ada2ba640dbb79b8d3a115369830f718. It would be nice to settle on something in DBI as well, as this generic should really be defined there.

I think reversing the order of the arguments like I did is pretty important; i.e. the highest level argument should the furthest right. This approach would also allow the generic to skip names for `schema` and `catalog` all together if desired and just take additional arguments as `...`.

Also I think you need to pass the connection object to `dbId` so that you can properly escape the identifiers and potentially use a different schema separator if needed.

**Comment by ldfreight** [comment]
schema support is a great addition. 
Is there a publication to CRAN to be expected soon?

**Comment by ldfreight** [comment]
Hello,

thank you for the recent addition. Support for schema is great. 

 I am using DBI 0.75

`DBI::dbWriteTable(conn = con, name = DBI::Id(schema="dbo", name="mytable"), value = df, append=TRUE)
`
however this returns 

> unable to find an inherited method for function 'dbWriteTable' for signature '"Microsoft SQL Server", "SQL", "missing"'

Is this the correct usage of `Id` ?

thank you

**Comment by mmastand** [comment]
That looks like the right usage to me. I'm also having this same problem with `Id` and DBI 0.7-15 (installed from github). The following:
```
res <- DBI::dbWriteTable(conn = con,
                         name = DBI::Id(catalog = "testing", schema = "dbo", name = "test_table"),
                         value = v,
                         append = TRUE)
```
returns
> Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbWriteTable’ for signature ‘"Microsoft SQL Server", "SQL", "missing"’

**Comment by hadley** [comment]
Commenting on a closed issue is not a good way to get help. You probably need to file an issue with whatever package you are using to connect to SQL server.

**Comment by krlmlr** [comment]
Thanks. `Id()` is called `Table()` in the most recent CRAN version. Please file a new issue, preferably with your DBI backend package, as @hadley suggested.

**Comment by krlmlr** [comment]
Oh, I'm confused, it's `Id` now. The usage looks correct, but the DBI backend needs to support it.

**Comment by mmastand** [comment]
Thanks, I'll move this to `odbc`.
