### ISSUE TITLE
Unable to return decimal(17, 7) column automatically

### ISSUE THREAD

**Issue by MichaelChirico** [r-dbi/DBI#247]
I've got a table like this in `PrestoDB`:

```
dbGetQuery(my_conn, 'describe my_table')
#    Column          Type Extra Comment
# 1:     V1       integer              
# 2:     V2       varchar              
# 3:     V3 decimal(17,7)              
# 4:     V4     timestamp              
# 5:     V5     timestamp                   
```

I think that `DBI` doesn't know how to process the `decimal(17, 7)` column, `V3`:

```
dbGetQuery(my_conn, 'select V3 from my_table')
```
> Error in .jcall(rp, "I", "fetch", stride, block) : 

>   java.sql.SQLException: Value is not a number: java.lang.String

if I `cast(V3 as double)` it returns as expected; but `select * from my_table` in a database GUI, e.g. I use DBeaver, works as expected, no casting necessary, which is why I think this is a `DBI` bug. 

A more reproducible version (may require PrestoDB connection?)

```
dbGetQuery(my_conn, 'select cast(123.4356789 as decimal(17, 7)')
```

**Comment by krlmlr** [comment]
Thanks. How does your `dbConnect()` call look like?

**Comment by MichaelChirico** [comment]
not sure what level of detail you need/what exactly is considered private, here's something minimal, happy to elaborate as much as I can

```
driver = JDBC("com.xxx.jdbc.xxx", "/path/to/xx-jdbc-xx.jar")
conn = dbConnect(driver, "jdbc:xx:port/hive/public", "user", "pw")
```

**Comment by krlmlr** [comment]
Thanks, this certainly helps. Have you tried the _RPresto_ package?

**Comment by dernst** [comment]
The error occurs in `RJDBC`, which already treats `DECIMAL` as `double`. The exception occurs in JDBC because apparently the JDBC-driver sends `DECIMAL(17,7)` columns as strings (or the presto JDBC driver can't or won't implicitly convert to double). Not sure what a good solution would be; always treating `DECIMAL` columns as character in RJDBC might break other databases.

**Comment by krlmlr** [comment]
I'm not familiar with _RJDBC_, JDBC or Presto. But the problem described here doesn't look like it's caused by the _DBI_ package, because the DBI backend (in this case _RJDBC_) is responsible for translating R data types to whatever the database driver (in this case JDBC) understands.

Strategically, maybe a new `decimal` data type, akin to `hms` and `blob`, could help? But this would need support from _RJDBC_ too. https://stackoverflow.com/q/16960167/946850 asks about such a data type in R, with no definite answer.

Could you please take this to the _RJDBC_ issue tracker?
