### ISSUE TITLE
function dbReadTable argments error (unecessary  quotation marks?)

### ISSUE THREAD

**Issue by maurfols** [r-dbi/DBI#272]
Package: DBI Version: 1.0.0
R version 3.5.2

I can't use the function dbReadTable, it returns an error related to non-existence of a table i've just created in my Oracle DB. It follows an simple example of the message and corresponding R code. I've not pasted the entire connection code once it is related to my oracle environment.

Code:
JDBCdrv <- JDBC("oracle.jdbc.OracleDriver", classPath = ...
JDBCcon <- dbConnect(JDBCdrv,  ...
irisB <- iris
colnames(irisB) <- c("SepalLength", "SepalWidth",  "PetalLength", "PetalWidth",  "Species")
dbWriteTable(JDBCcon, "irisB", irisB)
recovery_data <- dbReadTable(JDBCcon, "irisB")

Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT * FROM "irisB" (ORA-00942: a tabela ou view nÃ£o existe
) 
althout this works perfectly:
dbGetQuery(JDBCcon, paste0("select * from irisB")

Loos like the dbReadTable is passing an extra quaotation marks in the select statement. it should be:
"select * from irisB" but instead is:
"select * from "irisB""

**Comment by krlmlr** [comment]
Thanks. Can you please try the following two options, so that we can better understand the problem:

```r
# Avoid quoting
dbWriteTable(JDBCcon, SQL("irisB"), irisB)
# Use uppercase
dbWriteTable(JDBCcon, "IRISB", irisB)
```

What does `dbListTables()` return?

According to section 8 in [the Oracle docs](https://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements008.htm), unquoted identifiers are interpreted as uppercase, whereas quoted identifiers are not converted. The default implementation of `dbWriteTable()` (and perhaps also the _JDBC_ one) quotes all identifiers, the `SQL()` in the example above avoids this.

**Comment by maurfols** [comment]
Thank you for your prompt answer.

I've tried both dBWriteTable commands, they sucessfully create the table in the Oracle DB

dbListTables return hundreds of tables, so I used this instead:
dbGetQuery(JDBCcon, "SELECT table_name FROM user_tables")
which returns only my tables and allowed me to assure the irisB table has been created.

Following your information about Oracle docs quoted identifiers, I've tried and had sucess to use the dBReadTable function:
recovery_data <- dbReadTable(JDBCcon, "IRISB")
I've just used all uppercase.

Thank you again. problem solved.
